### ISSUE TITLE
Make the config options for schema and structure more obvious

### ISSUE THREAD

**Issue by pwalsh** [okfn/spd-admin#17]
# Description

The `dq.json` config file provides direct access to all configuration options for GoodTables, the tool used to actually assess and generate the data quality reports.

In terms of the dimensions for assessment, this means that a data set can be assessed on:
- Structure of the data file.
- Structure and Schema, where a schema is provided for each data file.
- Structure and Schema, where a [schema is inferred](https://github.com/frictionlessdata/goodtables/blob/e6f5427197d1da7936b56db557068bad4fea4a82/goodtables/processors/schema.py#L87) from the start of each file, and then used to assess the rest of the file.

All these options should be made clearer in the README, as part of a section on the ways the tool can be configured to assess data quality.
# Tasks
- [x] Document the various structure and schema options for assessing data quality in the README
- [x] Ensure that we have a version of each assessment configuration live somewhere (the version with a schema for each file can be the uk25k dashboard) that we can link to: use our example CKAN instances. It might show some interesting differences when assessing without schema vs. inferred schema, for example.

**Comment by georgiana-b** [comment]
@pwalsh For the second task, you mean making different databases with a live dashboard for each? Also, if the purpose is comparison, maybe it would be better to use the same dataset (ex. uk25k) for all the examples, but with different settings for structure and schema?

**Comment by pwalsh** [comment]
@georgiana-b just choose one example database (whichever one makes sense), and deploy multiple dashboards for it with different config settings.

**Comment by georgiana-b** [comment]
Temporarily unable to deploy examples because [npm registry is down](https://github.com/npm/npm/issues/13284). :heart:JS
