### ISSUE TITLE
Issues with usage of `datapackage.json` file

### ISSUE THREAD

**Issue by georgiana-b** [okfn/spd-admin#20]
According to #15, the project should include a default `datapackage.json` file that contains schemas for the files used by the CLI and metadata about the project (replacing `instance.json` file).  A _project specific_ `datapackage.json` file will be generated from the _default_ if it doesn't exist when the `dq generate` command is used or when the `dq deploy` is used and the `last_modified` field inside must be updated.
However, since internally the _default_ `datapackage.json` file is used, inconsistencies  between the _project specific_  `datapackage.json` file and the contents of the files can appear when the _default_ and the _project specific_ `datapackage.json` files are out of sync.

Outline of some of the issues:
1. When using the `dq generate` command:
   - If a `datapackage.json` file already exists:
     - don't make another one (approach used in #19) => can lead to inconsistencies
       - _potential solution_: Compare the default schema for `source_file` & `publisher_file` with their equivalents from the project `datapackage.json`. If they are different, issue a prompt asking the user
         if they wish to overwrite the schemas in their `datapackage.json` + advise to use a custom generator if they don't. Proceed further or not depending on the answer.
     - make another one:
       - with the same name (instead of the existing one) => can lead to loss of data
       - with a different name telling the user to reconcile them =>  more effort for the user + still not reliable
   - If a `datapackage.json` is generated:
     - but the `dq run` command is not issued afterward => can lead to project specific `datapackage.json` containing resources that the project doesn't
       - _potential solution_:  At this step, generate the `datapackage.json` file containing only the `source_file` and `publisher_file` resources and add the other resources as they get generated (in the `dq run`)
     - but edited badly by the user
       - _potential solution_: Add another command that can issue a [minimal datapackage validation](https://github.com/frictionlessdata/datapackage-py#validating-a-data-package)
2. When using `dq run`:
   - If a `datapackage.json` file already exists:
     - but it doesn't have schemas for `run_file`, `performance_file` and `result_file`:
       - _potential solution_: add them (optionally overwrite them if they are there just to make sure)
     - but it doesn't have schemas for `source_file`  `publisher_file`:
       - _potential solution_: add them using [infer schema](https://github.com/frictionlessdata/jsontableschema-py#infer)
   - If a `datapackage.json` file doesn't exist:
     - create it from default (approach used in #19) =>  can lead to inconsistencies
       - _potential solution_: overwrite the generated `datapackage.json` schemas for `source_file`, `publisher_file` with [inferred schemas](https://github.com/frictionlessdata/jsontableschema-py#infer)
     - don't create it (as with `instance.json` file, if it doesn't exists it might not be wanted)

It all depends on whether we consider the existence of `datapackage.json` mandatory and how concerned we should be with its correctness. 

The potential solutions here are just the best ideas I had. Feedback is needed. Alternatives are welcomed.

**Comment by pwalsh** [comment]
Lots of points to address, so I will not address all at once.

Once first obvious thing: you have tied the creation of a `datapackage.json` to the generate command. It might be better to add a new init or similar command that generates the user's data dir with a `datapackage.json`. You could then add a function that checks of the current `datapackage.json` is valid for the database. Then, commands like generate can use the validation check before running.

Second, all the things in your point 2 can be solved by the above (init and check commands).

In general, yes, the `datapackage.json` is definitely mandatory.

**Comment by pwalsh** [comment]
@georgiana-b what about my above comments? Would this not solve the major points here?

**Comment by georgiana-b** [comment]
I think it's a good workflow. However, some of the issues are still uncovered:
1. How should the `datapackage.json` generated in `init` look like? 
   
   I think we should infer the schema for resources already present in the `data` folder and clone `datapackage.default.json` if there aren't any.
   
   Also, in order to avoid creating check errors ourselves, we should create the `result_file`, `run_file` and `performance_file` along with their schema as part of the `init` step and fill them in afterward. 
2. What happens in `init` if the `data` folder and `datapackage.json` already exist?
   
   I suppose we run the check and raise an error if the resources in `datapackage.json` and `data` folder don't match.
3. What happens in the `generate`, `run` commands if the check fails? 
   
   I propose we abort mission with a relevant error. 
4. Considering the scope of this tool, should we even be so concerned about the _correctness_ of the data package?  
   
   These issues are questionable. We could just leave it as it is now (using the `datapackage.default.json` internally) and let the project administrator deal with the `data` folder and `datapackake.json` file (even though it would make the tool less pleasant to use).
   
   It also depends on how much we want to count on it in other tools (ex: frictionlessdata/data-quality-dashboard#67).

**Comment by pwalsh** [comment]
Hi!
1. It should look as described in [this issue](https://github.com/frictionlessdata/data-quality-cli/issues/15). i.e: empty name property, and a resources array with an entry for each file required for the "database"
2. Yes. Raise an error
3. Raise an error
4. Yes.
