### ISSUE TITLE
Update all example instances

### ISSUE THREAD

**Issue by georgiana-b** [okfn/spd-admin#33]
Update all example instances of dq-cli to the latest changes: 
- [ ] https://uk-25k-structure-only.herokuapp.com
- [ ] https://uk-25k-given-schema.herokuapp.com/
- [ ] https://uk-25k-inferred-schema.herokuapp.com/
- [ ] data-quality-uk-25k-spend master and https://uk-25k.herokuapp.com/

**Comment by pwalsh** [comment]
@georgiana-b no, we are done with the example now, please do these https://github.com/frictionlessdata/data-quality-dashboard/issues/68
